name: trader_app
description: AI-powered stock recommendation app based on legendary traders' strategies
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  
  # Internationalization
  intl: ^0.20.2
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Backend & Database (백엔드 개발 완료 후 연동 예정)
  # supabase_flutter: ^2.3.2
  
  # Video Player
  video_player: ^2.8.2
  chewie: ^1.7.4
  
  # Utils
  shared_preferences: ^2.2.2
  http: ^1.2.0
  
  # Charts
  fl_chart: ^0.68.0
  
  # Image & File
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  
  # Permissions
  permission_handler: ^11.2.0
  
  # In-App Purchases
  in_app_purchase: ^3.1.13
  
  # Supabase
  supabase_flutter: ^2.3.0
  
  # Authentication
  google_sign_in: ^5.4.4
  firebase_auth: ^4.16.0
  firebase_core: ^2.32.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Test Utilities
  mockito: ^5.4.4
  build_runner: ^2.4.8
  fake_async: ^1.3.1
  integration_test:
    sdk: flutter
  
  # Coverage
  coverage: ^1.7.2

flutter:
  generate: true
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
  
  # Fonts (if needed)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700