// Mocks generated by Mockito 5.0.0 from annotations
// in trader_app/test/unit/services/subscription_service_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;
import 'package:in_app_purchase/in_app_purchase.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i2.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseQueryBuilder from(String table) => (super.noSuchMethod(
        Invocation.method(
          #from,
          [table],
        ),
        returnValue: _FakeSupabaseQueryBuilder_0(),
      ) as _i2.SupabaseQueryBuilder);
}

class _FakeSupabaseQueryBuilder_0 extends _i1.Fake
    implements _i2.SupabaseQueryBuilder {}

/// A class which mocks [PurchaseDetails].
///
/// See the documentation for Mockito's code generation for more information.
class MockPurchaseDetails extends _i1.Mock implements _i3.PurchaseDetails {
  MockPurchaseDetails() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get productID => (super.noSuchMethod(
        Invocation.getter(#productID),
        returnValue: '',
      ) as String);

  @override
  String? get purchaseID => (super.noSuchMethod(
        Invocation.getter(#purchaseID),
        returnValue: null,
      ) as String?);

  @override
  _i3.PurchaseVerificationData get verificationData => (super.noSuchMethod(
        Invocation.getter(#verificationData),
        returnValue: _FakePurchaseVerificationData_1(),
      ) as _i3.PurchaseVerificationData);

  @override
  String get transactionDate => (super.noSuchMethod(
        Invocation.getter(#transactionDate),
        returnValue: '',
      ) as String);

  @override
  _i3.PurchaseStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i3.PurchaseStatus.pending,
      ) as _i3.PurchaseStatus);
}

class _FakePurchaseVerificationData_1 extends _i1.Fake
    implements _i3.PurchaseVerificationData {}