// Mocks generated by Mockito 5.0.0 from annotations
// in trader_app/test/unit/services/watchlist_service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;
import 'package:trader_app/services/finnhub_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i2.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseQueryBuilder from(String table) => (super.noSuchMethod(
        Invocation.method(
          #from,
          [table],
        ),
        returnValue: _FakeSupabaseQueryBuilder_0(),
      ) as _i2.SupabaseQueryBuilder);
}

class _FakeSupabaseQueryBuilder_0 extends _i1.Fake
    implements _i2.SupabaseQueryBuilder {}

/// A class which mocks [FinnhubService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFinnhubService extends _i1.Mock implements _i4.FinnhubService {
  MockFinnhubService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> getStockQuote(String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStockQuote,
          [symbol],
        ),
        returnValue: _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> searchSymbol(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchSymbol,
          [query],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);
}